# Generated by Django 5.2.9 on 2026-01-06 23:14

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="code",
            field=models.CharField(
                default=medicos.models.generar_code, max_length=32, unique=True
            ),
        ),
    ]
